# In doc/_quarto.yml
project:
  type: website
  output-dir: _site
  # preview:
  #   port: 7000

format:
  html:
    # code-fold: true
    # code-summary: "Show the code"
    theme: 
      light: flatly
      dark: darkly
    css:
      - api/_styles-quartodoc.css
      - styles.css
    fontsize: 1.1em
    linestretch: 1.7
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

    toc: true
    toc-title: Contents
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    highlight-style: github
    link-external-icon: true
    link-external-newwindow: true
    eqn-number: true

website:
  title: "jAxon"
  favicon: favicon.png
  sidebar:
    title: false
    logo: logo.png
    style: "docked"
    search: true
    type: "dark"
    tools:
      - icon: github
        href: https://github.com/wendtalexander/jaxon
    contents:
      - text: "Introduction"
        href: "index.qmd"
      - section: "Tutorials"
        contents:
        - jax.qmd
        - lif.qmd
        - alif.qmd
        - adex.qmd
        - punit.qmd
      - section: "P-Unit model comparison"
        contents:
        - baseline.qmd
        - spectral.qmd
        - performance.qmd
      - section: "Power Spectra"
        contents:
        - ou.qmd
      - section: "API"
        href: "api/index.qmd"
        contents:
        - section: models
          contents:
            - api/models.lif.qmd
            - api/models.adex.qmd
            - api/models.alif.qmd
            - api/models.punit.qmd
        - section: stimuli
          contents:
            - api/stimuli.noise.qmd
        - section: analyze
          contents:
            - api/analyze.baseline.qmd
            - api/analyze.spectral.qmd

quartodoc:
  package: jaxon
  dir: "api"
  css: api/_styles-quartodoc.css
  renderer:
    style: markdown
    table_style: description-list
  sections:
    - title: Model
      desc: Simulation models which you can use
      contents:
        - models.lif
        - models.adex
        - models.punit
        - models.alif
    - title: stimulus
      desc: Stimuli functions
      contents:
        - stimuli.noise
    - title: analyze
      desc: Anylyze functions
      contents:
        - analyze.baseline
        - analyze.spectral

execute:
  freeze: auto
